#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:t p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:t todo:t |:t

#+TITLE: About
#+OPTIONS: ':nil -:nil ^:{} num:nil toc:nil
#+AUTHOR: Stanislav Arnaudov
#+DATE: <2018-06-15 Thu>
#+EMAIL: stanislav_ts@abv.bg
#+CREATOR: Emacs 25.2.2 (Org mode 9.1.13 + ox-hugo)
#+HUGO_FRONT_MATTER_FORMAT: toml
#+HUGO_LEVEL_OFFSET: 1
#+HUGO_PRESERVE_FILLING:
#+HUGO_SECTION: ./
#+HUGO_BASE_DIR: ~/code/blog-hugo-files
#+HUGO_PREFER_HYPHEN_IN_TAGS: t 
#+HUGO_ALLOW_SPACES_IN_TAGS: nil
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DATE_FORMAT: %Y-%m-%dT%T%z
#+DESCRIPTION: Simple and basic description of who I am and what the hell I'm all about.
#+HUGO_DRAFT: false
#+KEYWORDS:
#+HUGO_TAGS:
#+HUGO_CATEGORIES:
#+HUGO_WEIGHT: 90


* Formal CV

A PDF of my real [[file:posts/files/cv.pdf][resume]].


* My assigned character

I was born a human and I'm supposed to live on the planet till my body gives up and it's no longer suitable for sustaining the social construct that one would call "life"... or at least I am said so. I reserve my right to have speculations about this whole "dying"-thing. I popped into existence in the almost ex-soviet republic of Bulgaria where I've spent a good portion of my development into a fully-fledged and normally functioning carbon unit. After almost a fifth of a century there I've decided to change my location to the vicinity of central Europe. Germany to be more precise. Here I am currently studying Computer Science at the [[https://www.kit.edu/][Karlsruer Institut für Technologie (KIT)]]. I quite like it here as for now it's the place that allows me to extend my skill set, knowledge base and general level of awesomeness through learning about how computers work, how to tell them what you want them to do and other fun things about the surrounding world.


* Relevant interests of choice
As previously implied, the delusion I've chosen to believe in is that I'll do CS (Computer Science) related things till the rest of my conscious earth-life. With the years (I am not that old, just obnoxious) I've developed an interest in some narrower areas in the computer world.
1. A special place in my heard is dedicated to Artificial Intelligence. No, not only the Machine Learning parts. The whole thing! The things in [[http://aima.cs.berkeley.edu/][Artifcial Intelligence: A modern approach]]. Not only the parts that are rough and massive number-crunching by the CPU cores but also the parts that are plain old beauty. The parts that model the human brain. This quote summarises my views on AI nicely.
  #+BEGIN_QUOTE
  Algorithms, enabled by constraints, exposed by representations that support models, targeted at thinking, perception, and action.
  -- [[https://www.csail.mit.edu/person/patrick-winston][Patrick Winston]]
  #+END_QUOTE
  I believe that this section deserves a subsection for its own! So, over the years I've acquired tastes for:
   - Computer vision and image processing and evaluation - I've had several times to write my own computer vision/image processing library in java at the time (but then some horrible events happened to my codebase so sorry, can't back this statement with code 😥 ).
   - Machine Learning. Different types of [[https://en.wikipedia.org/wiki/Perceptron][perceptrons]], neural networks, regression models, classification models, trees, support vector machines, deep networks... etc. Many of those I've implemented once for myself and the sake of learning and understanding how everything works
   - Linear Programming - while most people hated the course where this thing is learned at UNI, I kinda loved it. [[https://en.wikipedia.org/wiki/Simplex_algorithm][Simplex]] can be quite the gem. Sadly, I am yet to implement it for myself.
   - Generic Algorithms
   - Natural Language Processing
   - Autonomous agents and group behaviors - Man, [[https://natureofcode.com/][this book (The nature of code)]] blew me away in unimaginable ways. Not exactly AI, but still!
   - Statistical Inference - Probability theory can also be a beautiful thing if you manage to push past the "statistics".
    
   As much as I loved AI, I only had the opportunity to have the time and necessity to learn about all the cool tools that exist in the python ecosystem that enable you to make awesome machine learning and AI applications. Libraries and tool-kits as /numpy/, /SciKit-learn/, /Tensorflow/, /Keras/, /Eward/... etc.

2. Computer Graphics/Game engine design - as every naive young boy at one point in my life I wanted to make games for a living. Unfortunately, I was also kinda smart enough to start doing something even thou I had no idea what was I doing. The first engines that I've "used" were Unity, Unreal Engine 3 and... Macromedia Studio 8. Myeah, that last one is a thing that existed and it's not game engine at all but hell, I was pretty much making a flash game on it. Over the years my focus shifted and transitioned to programming but my interest in games stayed. Thanks to that, at some point I picked up a little OpenGL, a little general 2D/3D Rendering and concepts and a good amount of making a rudimentary engine that can run a "game". At university, I took a course in Computer Graphics where I learned a whole lot of other interesting topics such as ray tracing, realistic image generation, seep-up structures, colors, and others. As far as I'm concerned - I still find everything in the subject incredibly exciting.
3. EMACS! [[https://www.gnu.org/software/emacs/][EMACS]] is everything. Emacs is an operating system, lacking a decent text editor. At my first job, I saw my supervisor using it and then a guy told me not to touch that thing ever. But I did! And I hated it! It was so difficult and unintuitive. Then I forced myself to use it because every other editor/IDE was a pain to use when programming in C++. I spend a good couple of days configuring Emacs and... I made it usable. Then I started investing more and more and it became second nature. An extension of my hands, if you will. And now I am writing this blog with Emacs. Be sure to check out my configuration file [[https://github.com/palikar/dotfiles/blob/master/.emacs.d/myinit.org][here]].
4. Web Development - it's one of the things where you learn even that you don't want. I am not proud of myself with this one but hey, it impresses the employers. I have my fair share with AnuglarJS, VueJS, Bootstrap, Foundation, JQuery, ExpressJS, and other little and big JavaScript libraries. On the back-end side, a have a little bit of experience with [[http://flask.pocoo.org/][Flask]]
5. Some small interests I've picked in recent times
   - Operating systems in general, Linux in general (Debian for life!) - It _really_ help to know what is happening on OS-level when writing c++.
   - CPU-Design and what happens in the computer of relatively low level - a lot of effects that happen on a transistor-ish level are exploitable in code, if you know they exist, of course.
   - Compiler Design - that one course at uni! Compilers are technological marvels, lexers and parser are awesome.
   - Functions optimization, Non-linear optimization, Computational linear algebra, Numerical analysis. In my defense being a bigger nerd doesn't really hurt your career.
   - Lambda calculus - a computational model that has a completely different way of reasoning about things. I love it. I fund the whole idea interesting, "fresh", mind-boggling and.....just different and unconventional.


* Supported Languages
- Java, C++, Python, HTML/CSS/JavaScript, ELisp
- Haskell, Prolog
- PHP, Scala, Processing


* Technologies
- git
- Tensorflow, SciKit-learn, Pandas, Jupytor, PyTorch
- Cmake, make, g++, Robot Operating System(ROS), RabbitMQ, OpenCV
- JavaFX/Java-Swing, JUnit, Maven 
- Frontend(AngularJS, VueJS), Backend(NodeJS, Express, Flask), Websockets, Karma, Jasmine, SQL
- LaTeX, [[https://orgmode.org/][Emacs Org-mode]], UML


* Current work
- Working as a research assistant at [[https://www.fraunhofer.de/en.html][Fraunhofer IOSB]]. I deal mainly with "intelligent systems".
- Right now I am taking part in a research-oriented practical course at my University. The goal is to write a research paper and publish it in two semesters. My work is dealing with the application of neural networks in the context of numerical simulations. 


* Previous work

- My Bachelor thesis had to do with Machine Learning, stochastic probability models (Bayesian Neural Networks and Mixture of Gaussian Process Experts) and data from pollution sensors. One of my supervisors currently working in [[https://www.h-its.org/en/][HITS]].

- At Uni I took a Practical Course in Computational Geometry about drawing curves (with BSplines) in the plane, doing tricks with them (finding a parallel curve, creating a closed curve, interpolating curve) and extending those to surfaces(tensor product surfaces)

- A practical course in software development - I and five other students, developing a Software product (a Web App) following the waterfall methodology (waterfall can be the better choice when you are new to everything)

- Algorithms Teaching assistant in [[https://www.kit.edu/][KIT]] - teaching basic data structures, algorithms for sorting, graphs and spanning trees, complexity, algorithm analysis, and algorithm engineering. Also, again, checking homework.

- Linear Algebra Teaching assistant in [[https://www.kit.edu/][KIT]] - teaching a bunch of people about basic mathematical notation, group theory, rings, bodies, vector spaces, and some other things. Also checking the homework of said people.



